Update StructCustomPlaceholder.java
APickledWalrus/skript-placeholders pull request #64
Opened 2024-08-23 23:30 UTC by EquipableMC

### Description
This simply adds `request` back for registering a placeholder. It seemed to have gotten removed in 1.7 but it existed in 1.6 and below

---
**Requirements:** none 
**Related Issues:** none

2024-08-23 23:40 UTC, APickledWalrus requested changes
it should be optional

2024-08-23 23:40 UTC, EquipableMC commented
> it should be optional

true, fixing now

2024-08-24 01:21 UTC, APickledWalrus approved these changes

2026-03-31 06:09 UTC, APickledWalrus commented
I guess I never got around to merging this. But, after thinking about it more again, I'm not really a huge fan of this word in the syntax. Thus, I'll be closing this. Thanks for your prior efforts though.

2026-03-31 06:09 UTC, closed without merging